
[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 17.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 5

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = """
fuzzy_navigate
"""
key = "F"
mods = "Control"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.94

[window.dimensions]
columns = 114
lines = 28

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["/Users/sri/.config/alacritty/catppuccin-mocha.toml"]
