
[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 4

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = """
fuzzy_navigate
"""
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bk"
key = "K"
mods = "Alt"

[window]
# decorations = "buttonless"
dynamic_padding = false
opacity = 0.94

[window.dimensions]
columns = 114
lines = 28

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"
